---
- name: "Create container_mirror_cert_paths"
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ container_mirror_cert_paths }}"
  tags: cert

- name: "Copy {{ container_mirror }} self-signed cert"
  copy:
    dest: "{{ item }}/docker-mirror.crt"
    content: "{{ container_mirror_cert }}"
  with_items: "{{ container_mirror_cert_paths }}"
  tags: cert

- name: Install registries-conf-ctl 
  pip:
    name: git+https://github.com/sebastian-philipp/registries-conf-ctl
    state: latest
  tags: registries-conf-ctl

- name: "Check for docker's daemon.json"
  stat:
    path: "{{ container_service_conf }}"
  when:
    - "'docker.io' in container_packages"
    - "'podman' not in container_packages"
  register: container_conf

- name: "Create {{ container_service_conf }} if necessary"
  copy:
    dest: "{{ container_service_conf }}"
    content: "{}"
  when:
    - "'docker.io' in container_packages"
    - "'podman' not in container_packages"
    - container_conf.stat.exists == False

- name: Add local docker.io registry mirror
  command: registries-conf-ctl add-mirror docker.io "{{ container_mirror }}"
  environment:
    PATH: /usr/local/bin:/usr/bin
  tags: registries-conf-ctl

# not very elegant but it's a workaround for now
- name: Restart docker service
  service:
    name: docker
    state: restarted
  when: "'docker.io' in container_packages"
  # There's an issue with ansible<=2.9 and our custom built kernels (5.8 as of this commit) where the service and systemd modules don't have backwards compatibility with init scripts
  ignore_errors: "{{ 'ceph' in ansible_kernel }}"
